# -*- mode: python ; coding: utf-8 -*-


block_cipher = None

added_files = [('JBExtractor_v1.1.ui', '.'),
			   ('jb_loading.ui', '.'),
			   ('jb_help.ui', '.'),
			   ('jb_warning_step1_1.ui', '.'),
			   ('jb_warning_step1_2.ui', '.'),
			   ('jb_warning_step1_3.ui', '.'),
			   ('jb_warning_step1_4.ui', '.'),
			   ('jb_warning_step3.ui', '.'),
			   ('./icons/help_main_1.png', './icons'),
			   ('./icons/help_step1_1.png', './icons'),
			   ('./icons/help_main_1.png', './icons'),
			   ('./icons/help_step3_1.png', './icons'),
			   ('./icons/help_step4_1.png', './icons'),
			   ('./icons/back_arrow.png', './icons'),
			   ('./icons/next_arrow.png', './icons'),
			   ('./icons/play.png', './icons'),
			   ('./icons/settings.png', './icons'),
			   ('./icons/upload.png', './icons'),
			   ('./icons/virus-scan.png', './icons'),
			   ('./icons/faq.png', './icons'),
			   ('./icons/home.png', './icons'),
			   ('./icons/home2.png', './icons'),
			   ('./icons/menu.png', './icons'),
			   ('./icons/download.png', './icons'),
			   ('./icons/download2.png', './icons'),
			   ('./icons/internet.png', './icons'),
			   ('./icons/JB_Logo.png', './icons'),
			   ('./icons/minimize.png', './icons'),
			   ('./icons/maximize.jpg', './icons'),
			   ('./icons/close.png', './icons'),
			   ('./icons/clock.png', './icons'),
			   ('./icons/calendar.png', './icons'),
			   ('./icons/next-week.png', './icons'),
			   ('./icons/back-week.png', './icons'),
			   ('./icons/add-event.png', './icons'),
			   ('./icons/cancelled.png', './icons'),
			   ('./icons/reload.png', './icons'),
			   ('./icons/back.png', './icons'),
			   ('./icons/list.png', './icons'),
			   ('./icons/complete.png', './icons'),
			   ('./icons/question.png', './icons'),
			   ('./icons/warning_sign.png', './icons'),
			   ('./icons/spinner.gif', './icons'),
			   ('JBExtract_icon.ico','.')]

a = Analysis(['JBExtractor_v1.3.py'],
             pathex=['C:\\Users\\JH\\Desktop\\JB_UI'],
             binaries=[],
             datas=added_files,
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [],
		  icon='C:\\Users\\JH\\Desktop\\JBExtractor\\JBExtract_icon.ico',
          name='JBExtractor',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False,
		  uac_admin=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )
