[uwsgi]

module = wsgi

socket = /home/goldory/myproject.sock
chmod-socket = 666
vacuum = true

daemonize = /home/goldory/uwsgi.log
processes = 8
threads = 2
virtualenv = /home/goldory/jebobada/venv

enable-threads = true
die-on-term = true
#plugins = python
